import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section class="portfolio">
        <div class="project">
          <img src="project1.jpg" alt="Project 1"/>
          <h2>Project 1</h2>
          <p>Description of Project 1</p>
          <a href="#">View Project</a>
        </div>
        
        <div class="project">
          <img src="project2.jpg" alt="Project 2"/>
          <h2>Project 2</h2>
          <p>Description of Project 2</p>
          <a href="#">View Project</a>
        </div>
      </section>
    </>
  );
}
